repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python_venv
        types: [python]
        args:
          - "--remove-all-unused-imports"
          - "--in-place"
          - "--ignore-init-module-imports"
      - id: black
        name: black
        entry: black
        language: python_venv
        types: [python]
      - id: isort
        name: isort
        entry: isort
        language: python_venv
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: python_venv
        types: [python]
        additional_dependencies:
          - "autoflake"
          - "black"
          - "isort"

default_language_version:
  python: python3.9
default_stages: ["commit"]
